### ISSUE TITLE
Phase 01 Tasks

### ISSUE THREAD

**Issue by MoeeinAali** [MelikaAlizadeh/Mobile-Project#1]
## Todo-List
- [x] Create a GitHub repository and define the issue
- [x] Identify entities of  project 
- [x] Room Database
- [x] UI/UX of Project
- [x] Front-End
- [x] Back-End
- [x] Connect Database to Back-End
- [x] Connect Back-End to Front-End

## Front-End Task:
- [x] Splash Screen
- [x] Unboard1
- [x] Unboard2
- [x] Main Menu
- [x] Profile Menu
- [x] Register
- [x] Login
- [x] Quiz Part
- [x] Training Part
